#!/usr/bin/env bash
set -e
[ -n "$DENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
		shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load denv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo 'eval "$(denv init -)"'
    echo
  } >&2

  exit 1
fi

mkdir -p "${DENV_ROOT}/"{shims,versions}

echo 'export PATH="'${DENV_ROOT}'/shims:${PATH}"'

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/denv.${shell}\""
  ;;
esac

if [ -z "$no_rehash" ]; then
  echo 'denv rehash 2>/dev/null'
fi

commands=(`denv commands --sh`)
IFS="|"
cat <<EOS
denv() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`denv "sh-\$command" "\$@"\`;;
  *)
    command denv "\$command" "\$@";;
  esac
}
EOS
