#!/usr/bin/env bash

# porting from rbenv-install

set -e
[ -n "$DENV_DEBUG" ] && set -x

if [ -z "$DENV_ROOT" ]; then
  DENV_ROOT="${HOME}/.rbenv"
fi

# Load shared library functions
eval "$(denv-util --lib)"

http() {
  local method="$1"
  local url="$2"
  [ -n "$url" ] || return 1

  if type wget &>/dev/null; then
    "http_${method}_wget" "$url"
  elif type curl &>/dev/null; then
    "http_${method}_curl" "$url"
  else
    echo "error: please install \`curl\` or \`wget\` and try again" >&2
    exit 1
  fi
}

http_get_curl() {
  curl -sSLf "$1"
}

http_get_wget() {
  wget -nv -O- "$1"
}

fetch_zip() {
  local package_name="$1"
  local package_url="$2"
  local package_filename="${package_name}.zip"

  rm -rf "$package_filename"
  echo "Downloading ${package_name}..." >&2
  { http get "$package_url" > "$package_filename"
  } || return 1

  {
    unzip "$package_filename" > /dev/null
    rm -f "$package_filename"
  } || return 1
}

fetch_tar_xz() {
  local package_name="$1"
  local package_url="$2"
  local package_filename="${package_name}.tar.xz"

  rm -rf "$package_filename"
  echo "Downloading ${package_name}..." >&2
  { http get "$package_url" > "$package_filename"
  } || return 1

  {
    tar xf "$package_filename" > /dev/null
    rm -f "$package_filename"
  } || return 1
}

install_dmd_package() {
    local package_name="$1"
    local package_url="$2"
    local package_path="$PREFIX/$package_name"

    fetch_zip "$package_name" "$package_url"
    rm -rf "$package_path"
    mkdir -p "$PREFIX"

    echo "Installing ${package_name} to ${package_path}"
    mv dmd2 "$package_name"
    mv "$package_name" "$PREFIX"
}

install_ldc_package() {
    local package_name="$1"
    local package_url="$2"
    local package_path="$PREFIX/ldc-$package_name"
    local arch_bin=""

    fetch_tar_xz "$package_name" "$package_url"
    rm -rf "$package_path"
    mkdir -p "$PREFIX"

    if [ "$os" = "osx" ]; then
        arch_bin="bin"
    elif [ "$os" = "linux" ]; then
        if [ "$arch" = "x86_64" ]; then
            arch_bin="bin64"
        else
            arch_bin="bin32"
        fi
    fi
    echo "Installing ${package_name} to ${package_path}"
    mv "ldc2-${package_name}-${os}-${arch}" "ldc-$package_name"
    mv "ldc-$package_name" "$PREFIX"
    mkdir -p "$package_path/$os"
    ln -s "$package_path/bin" "$package_path/$os/${arch_bin}"
}

# TODO: build from source
# TODO: support gdc

usage() {
  # We can remove the sed fallback once rbenv 0.4.0 is widely available.
  denv-help install 2>/dev/null || sed -ne '/^#/!q;s/.//;s/.//;1,4d;p' < "$0"
  [ -z "$1" ] || exit "$1"
}

list_definitions() {
  { for definition in "${DENV_ROOT}/share/d-build/"*; do
      echo "${definition##*/}"
    done
  } | sort
}

parse_options "$@"
for option in "${OPTIONS[@]}"; do
  case "$option" in
  "h" | "help" )
    usage 0
    ;;
  "l" | "list" )
    echo "Available versions:"
    list_definitions | sed 's/^/  /'
    exit
    ;;
  "v" | "verbose" )
    VERBOSE="-v"
    ;;
  * )
    usage 1
    ;;
  esac
done

DEFINITION="${ARGUMENTS[0]}"
if [ -z "$DEFINITION" ]; then
  usage 1
elif [ ! -e "$DEFINITION" ]; then
  BUILTIN_DEFINITION="${DENV_ROOT}/share/d-build/${DEFINITION}"
  if [ -e "$BUILTIN_DEFINITION" ]; then
    DEFINITION="$BUILTIN_DEFINITION"
  else
    echo "denv install: definition not found: ${DEFINITION}" >&2
    exit 1
  fi
fi

# for ldc
os=""
arch=""
if [ `uname` = "Darwin" ]; then
  os="osx"
  arch="x86_64"
elif [ `uname` = "Linux" ]; then
  os="linux"
  if [ `uname -m` = "x86_64" ]; then
    arch="x86_64"
  else
    arch="x86"
  fi
else
  echo "denv: unsupported env: `uname`"
  exit 1
fi

for script in $(denv-hooks install); do
  source "$script"
done

VERSION_NAME="${DEFINITION##*/}"
PREFIX="${DENV_ROOT}/versions"

source "$DEFINITION"
denv rehash
