#!/usr/bin/env bash
set -e
[ -n "$DENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: denv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "denv-$COMMAND" || command -v "denv-sh-$COMMAND")"
if grep -i "^# provide denv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
