#!/usr/bin/env bash
set -e
[ -n "$DENV_DEBUG" ] && set -x

DENV_VERSION_NAME="$(denv-version-name)"

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  print_version="$DENV_VERSION_NAME"
else
  hit_prefix="* "
  miss_prefix="  "
  print_version="$(denv-version)"
fi

for path in "${DENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    version="${path##*/}"

    if [ "$version" == "$DENV_VERSION_NAME" ]; then
      echo "${hit_prefix}${print_version}"
    else
      echo "${miss_prefix}${version}"
    fi
  fi
done
