#!/usr/bin/env bash
set -e
[ -n "$DENV_DEBUG" ] && set -x

# Provide denv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${DENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
